Repository mcndl13/SOEN-390-Mini-Capstone, pull requests merged in 2025-03, with the labels that each got.

#105 45 b61 shuttle integration, shuttle schedule
  lost-in-faubourg-app/assets/images/transportModes/bikeBlack.png
  lost-in-faubourg-app/assets/images/transportModes/bikeWhite.png
  lost-in-faubourg-app/assets/images/transportModes/busBlack.png
  lost-in-faubourg-app/assets/images/transportModes/busIcon.png
  lost-in-faubourg-app/assets/images/transportModes/busStation.png
  lost-in-faubourg-app/assets/images/transportModes/busWhite.png
  lost-in-faubourg-app/assets/images/transportModes/carBlack.png
  lost-in-faubourg-app/assets/images/transportModes/carWhite.png
  lost-in-faubourg-app/assets/images/transportModes/walkBlack.png
  lost-in-faubourg-app/assets/images/transportModes/walkWhite.png
  lost-in-faubourg-app/components/CampusMap.tsx
  lost-in-faubourg-app/components/DirectionsScreen.tsx
  lost-in-faubourg-app/components/HomeScreen.tsx
  lost-in-faubourg-app/package-lock.json
  lost-in-faubourg-app/package.json
  lost-in-faubourg-app/services/shuttleService.tsx
  lost-in-faubourg-app/utils/geometry.tsx
Labels: frontend, backend

#100 Accessibility Integration - Settings button
  lost-in-faubourg-app/app/index.tsx
  lost-in-faubourg-app/components/AccessibilitySettings.tsx
  lost-in-faubourg-app/components/CalendarIntegrationScreen.tsx
  lost-in-faubourg-app/components/CampusMap.tsx
  lost-in-faubourg-app/components/DirectionsScreen.tsx
  lost-in-faubourg-app/components/HomeScreen.tsx
  lost-in-faubourg-app/components/PointsOfInterestScreen.tsx
Labels: frontend, backend

#117 Indoor mapping
  lost-in-faubourg-app/app/index.tsx
  lost-in-faubourg-app/assets/floorplans/CC1.png
  lost-in-faubourg-app/assets/floorplans/Elevator_Logo.png
  lost-in-faubourg-app/assets/floorplans/Entrance_Logo.png
  lost-in-faubourg-app/assets/floorplans/Escalator_Logo.png
  lost-in-faubourg-app/assets/floorplans/Hall-1.png
  lost-in-faubourg-app/assets/floorplans/Hall-2.png
  lost-in-faubourg-app/assets/floorplans/Hall-8.png
  lost-in-faubourg-app/assets/floorplans/Hall-9.png
  lost-in-faubourg-app/assets/floorplans/MB-1.png
  lost-in-faubourg-app/assets/floorplans/MB-S2.png
  lost-in-faubourg-app/assets/floorplans/Mens_Bathroom_Logo.png
  lost-in-faubourg-app/assets/floorplans/Mixed_Bathrooms_Logo.png
  lost-in-faubourg-app/assets/floorplans/Stairs_logo.png
  lost-in-faubourg-app/assets/floorplans/VE-1.png
  lost-in-faubourg-app/assets/floorplans/VE-2.png
  lost-in-faubourg-app/assets/floorplans/VL-1.png
  lost-in-faubourg-app/assets/floorplans/VL-2.png
  lost-in-faubourg-app/assets/floorplans/Womens_Bathroom_Logo.png
  lost-in-faubourg-app/components/IndoorDirectionsScreen.tsx
  lost-in-faubourg-app/package-lock.json
  lost-in-faubourg-app/package.json
  package-lock.json
Labels: backend

#119 opening hours are available
  lost-in-faubourg-app/components/CampusMap.tsx
  lost-in-faubourg-app/components/polygonCoordinates.tsx
  lost-in-faubourg-app/services/openingHoursService.tsx
Labels: frontend

#114 Added an authentication sign in for google calendar
  .vscode/settings.json
  lost-in-faubourg-app/__tests__/__snapshots__/HomeScreen.test.jsx.snap
  lost-in-faubourg-app/app.config.js
  lost-in-faubourg-app/app.json
  lost-in-faubourg-app/components/CalendarIntegrationScreen.tsx
  lost-in-faubourg-app/components/HomeScreen.tsx
  lost-in-faubourg-app/coverage/coverage-final.json
  lost-in-faubourg-app/coverage/lcov-report/__tests__/helpers/directionsTestHelpers.tsx.html
  lost-in-faubourg-app/coverage/lcov-report/__tests__/helpers/index.html
  lost-in-faubourg-app/coverage/lcov-report/assets/images/transportModes/bikeBlack.png.html
  lost-in-faubourg-app/coverage/lcov-report/assets/images/transportModes/busBlack.png.html
  lost-in-faubourg-app/coverage/lcov-report/assets/images/transportModes/busStation.png.html
  lost-in-faubourg-app/coverage/lcov-report/assets/images/transportModes/carBlack.png.html
  lost-in-faubourg-app/coverage/lcov-report/assets/images/transportModes/carWhite.png.html
  lost-in-faubourg-app/coverage/lcov-report/assets/images/transportModes/index.html
  lost-in-faubourg-app/coverage/lcov-report/assets/images/transportModes/walkBlack.png.html
  lost-in-faubourg-app/coverage/lcov-report/assets/images/transportModes/walkWhite.png.html
  lost-in-faubourg-app/coverage/lcov-report/components/AccessibilitySettings.tsx.html
  lost-in-faubourg-app/coverage/lcov-report/components/CampusMap.tsx.html
  lost-in-faubourg-app/coverage/lcov-report/components/DirectionsScreen.tsx.html
  lost-in-faubourg-app/coverage/lcov-report/components/HomeScreen.tsx.html
  lost-in-faubourg-app/coverage/lcov-report/components/index.html
  lost-in-faubourg-app/coverage/lcov-report/components/polygonCoordinates.tsx.html
  lost-in-faubourg-app/coverage/lcov-report/index.html
  lost-in-faubourg-app/coverage/lcov-report/services/index.html
  lost-in-faubourg-app/coverage/lcov-report/utils/geometry.tsx.html
  lost-in-faubourg-app/coverage/lcov-report/utils/index.html
  lost-in-faubourg-app/coverage/lcov.info
  lost-in-faubourg-app/eas.json
  lost-in-faubourg-app/package-lock.json
  lost-in-faubourg-app/services/calendarService.tsx
  lost-in-faubourg-app/test-results/junit.xml
  lost-in-faubourg-app/tsconfig.json
  node_modules/@react-native-community/geolocation/android/.project
  node_modules/@react-native/gradle-plugin/.project
  node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/.project
  node_modules/@react-native/gradle-plugin/settings-plugin/.project
  node_modules/@react-native/gradle-plugin/shared-testutil/.project
  node_modules/@react-native/gradle-plugin/shared/.project
  node_modules/expo-application/android/.project
  node_modules/expo-asset/android/.project
  node_modules/expo-constants/android/.project
  node_modules/expo-crypto/android/.project
  node_modules/expo-file-system/android/.project
  node_modules/expo-font/android/.project
  node_modules/expo-keep-awake/android/.project
  node_modules/expo-linking/android/.project
  node_modules/expo-location/android/.project
  node_modules/expo-modules-core/android/.project
  node_modules/expo-web-browser/android/.project
  node_modules/expo/android/.project
  node_modules/react-native-maps/android/.project
Labels: backend, API

#145 Indoor navigation UI
  lost-in-faubourg-app/.gitignore
  lost-in-faubourg-app/App.tsx
  lost-in-faubourg-app/components/IndoorDirectionsScreen.tsx
  lost-in-faubourg-app/index.js
  lost-in-faubourg-app/metro.config.js
  lost-in-faubourg-app/package-lock.json
  lost-in-faubourg-app/package.json
Labels: enhancement, backend, refactoring
